version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    working_dir: /usr/src/website
    entrypoint: npm run start:dev -- --host 0.0.0.0
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - .:/usr/src/website

networks:
  network:
    driver: bridge
